### ISSUE TITLE
ValueError: Input contains NaN.  roc_auc_score

### ISSUE THREAD

**Issue by NaHCOOO** [mims-harvard/Raindrop#13]
--feature_removal_level no_removal 
Dataset used:  P12
args.dataset, args.splittype, args.reverse, args.withmissingratio, args.feature_removal_level P12 random False False no_removal
missing ratio list [0]
Split id: 1
9590 1199 1199 9590 1199 1199
- - Run 1 - -
Stop epochs: 20, Batches/epoch: 62, Total batches: 1240
Traceback (most recent call last):
  File "E:\code\GNN\Raindrop-main\code\Raindrop.py", line 343, in <module>
    train_auroc = roc_auc_score(train_y, train_probs[:, 1])
  File "E:\software\anaconda3\anaconda3_202309\envs\ptorch_py39\lib\site-packages\sklearn\utils\_param_validation.py", line 214, in wrapper
    return func(*args, **kwargs)
  File "E:\software\anaconda3\anaconda3_202309\envs\ptorch_py39\lib\site-packages\sklearn\metrics\_ranking.py", line 606, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "E:\software\anaconda3\anaconda3_202309\envs\ptorch_py39\lib\site-packages\sklearn\utils\validation.py", line 957, in check_array
    _assert_all_finite(
  File "E:\software\anaconda3\anaconda3_202309\envs\ptorch_py39\lib\site-packages\sklearn\utils\validation.py", line 122, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "E:\software\anaconda3\anaconda3_202309\envs\ptorch_py39\lib\site-packages\sklearn\utils\validation.py", line 171, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input contains NaN.

Process finished with exit code 1

**Comment by ahf0** [comment]
Hello,
I am facing the same problem. It's seems to be gradient exploding, you can verify that the loss ouputs contains Nan during training. Since in the paper they mention regularization coeffficients 0.02 which doesn't appears in the code.
I used some built-in regularization technics but it still does'nt work.
Please don't hesitate if you found a solution.
Thanks
